template = "https://github.com/giellalt/template-lang-und"
rev_id = 313
template_sha = "818c033010c3b7b906621cdeca79061f50bd93ed"

[replacements]
__GLOTTOLOG_ID__ = "waiw1244"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-waw"
__UND2C__ = "waw"
__UNDEFINED__ = "Waiwai"
__UND__ = "waw"
