template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "waiw1244"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-waw"
__UND2C__ = "waw"
__UNDEFINED__ = "Waiwai"
__UND__ = "waw"
